In [1]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("../data/raw")

df_scores = pd.read_csv(
    DATA_PATH / "2010-2025_scores.csv"
)

print(df_scores.shape)

df_scores.head()

(5832, 9)

,Season,Week,GameStatus,GameSlot,GameDate,AwayTeam,AwayScore,HomeTeam,HomeScore
0,2010,HALL OF FAME,FINAL,Sunday,August 8th,DAL,16.0,CIN,7.0
1,2010,PRESEASON WEEK 1,FINAL,Thursday,August 12th,CAR,12.0,BAL,17.0
2,2010,PRESEASON WEEK 1,FINAL,Thursday,August 12th,NO,24.0,NE,27.0
3,2010,PRESEASON WEEK 1,FINAL,Thursday,August 12th,OAK,17.0,DAL,9.0
4,2010,PRESEASON WEEK 1,FINAL,Friday,August 13th,BUF,17.0,WAS,42.0

In [2]:
df_scores.columns.tolist()

['Season',
 'Week',
 'GameStatus',
 'GameSlot',
 'GameDate',
 'AwayTeam',
 'AwayScore',
 'HomeTeam',
 'HomeScore']

In [3]:
df_scores["Week"].unique()

<StringArray>
[            'HALL OF FAME',         'PRESEASON WEEK 1',
         'PRESEASON WEEK 2',         'PRESEASON WEEK 3',
         'PRESEASON WEEK 4',                   'WEEK 1',
                   'WEEK 2',                   'WEEK 3',
                   'WEEK 4',                   'WEEK 5',
                   'WEEK 6',                   'WEEK 7',
                   'WEEK 8',                   'WEEK 9',
                  'WEEK 10',                  'WEEK 11',
                  'WEEK 12',                  'WEEK 13',
                  'WEEK 14',                  'WEEK 15',
                  'WEEK 16',                  'WEEK 17',
        'WILD CARD WEEKEND',      'DIVISIONAL PLAYOFFS',
 'CONFERENCE CHAMPIONSHIPS',                 'PRO BOWL',
               'SUPER BOWL',                  'WEEK 18']
Length: 28, dtype: str

In [4]:
exclude_weeks = [
    "HALL OF FAME",
    "PRESEASON WEEK 1",
    "PRESEASON WEEK 2",
    "PRESEASON WEEK 3",
    "PRESEASON WEEK 4",
    "PRO BOWL"
]

df_clean = df_scores[
    ~df_scores["Week"].isin(exclude_weeks)
].copy()

print(df_clean.shape)

df_clean["Week"].unique()

(4926, 9)

<StringArray>
[                  'WEEK 1',                   'WEEK 2',
                   'WEEK 3',                   'WEEK 4',
                   'WEEK 5',                   'WEEK 6',
                   'WEEK 7',                   'WEEK 8',
                   'WEEK 9',                  'WEEK 10',
                  'WEEK 11',                  'WEEK 12',
                  'WEEK 13',                  'WEEK 14',
                  'WEEK 15',                  'WEEK 16',
                  'WEEK 17',        'WILD CARD WEEKEND',
      'DIVISIONAL PLAYOFFS', 'CONFERENCE CHAMPIONSHIPS',
               'SUPER BOWL',                  'WEEK 18']
Length: 22, dtype: str

In [5]:
df_clean["HomeWin"] = (
    df_clean["HomeScore"] > df_clean["AwayScore"]
).astype(int)

df_clean[[
    "Season",
    "Week",
    "HomeTeam",
    "AwayTeam",
    "HomeScore",
    "AwayScore",
    "HomeWin"
]].head()

    Season    Week HomeTeam AwayTeam  HomeScore  AwayScore  HomeWin
65    2010  WEEK 1       NO      MIN       14.0        9.0        1
66    2010  WEEK 1       TB      CLE       17.0       14.0        1
67    2010  WEEK 1      BUF      MIA       10.0       15.0        0
68    2010  WEEK 1       NE      CIN       38.0       24.0        1
69    2010  WEEK 1      HOU      IND       34.0       24.0        1